namespace MirageClient.WPF.Services;

public sealed class LocalizationService
{
    private readonly Dictionary<string, Dictionary<string, string>> _translations = new()
    {
        ["en-US"] = new()
        {
            ["AppTitle"] = "MIRAGE",
            ["Tagline"] = "Native Windows proxy client",
            ["Overview"] = "Overview",
            ["Profiles"] = "Profiles",
            ["Diagnostics"] = "Diagnostics",
            ["Settings"] = "Settings",
            ["StatusOnline"] = "Connected",
            ["StatusOffline"] = "Core offline",
            ["OverviewTitle"] = "Connection overview",
            ["OverviewDesc"] = "See transport status, current proxy mode, and desktop capture coverage at a glance.",
            ["ProfileListTitle"] = "Profiles",
            ["ProfileListDesc"] = "Import MIRAGE nodes and switch the active connection.",
            ["DiagnosticsTitle"] = "Diagnostics",
            ["DiagnosticsDesc"] = "Check the live proxy stack and copy a complete report when something still bypasses MIRAGE.",
            ["SettingsTitle"] = "Settings",
            ["SettingsDesc"] = "Keep language, tray behavior, and system proxy policy in one native settings page.",
            ["HttpProxy"] = "HTTP / HTTPS",
            ["Socks5"] = "SOCKS5",
            ["Upload"] = "Upload",
            ["Download"] = "Download",
            ["Rate"] = "Throughput",
            ["SystemProxy"] = "System proxy",
            ["Import"] = "Import",
            ["Refresh"] = "Refresh",
            ["Connect"] = "Connect",
            ["Disconnect"] = "Disconnect",
            ["Language"] = "Language",
            ["LanguageSystem"] = "Follow system",
            ["LanguageZh"] = "Chinese",
            ["LanguageEn"] = "English",
            ["CoreVersion"] = "Core version",
            ["ProtocolVersion"] = "Protocol version",
            ["Health"] = "Health",
            ["Ready"] = "Ready",
            ["Running"] = "Running",
            ["LogEmpty"] = "No core logs yet.",
            ["NoProfiles"] = "No profiles imported yet.",
            ["ImportHint"] = "Paste a mirage:// link to add a profile to the local client library.",
            ["CaptureGap"] = "Some software still needs TUN or service capture to match mainstream clients.",
            ["TrayOpen"] = "Open MIRAGE",
            ["TrayConnect"] = "Connect",
            ["TrayDisconnect"] = "Disconnect",
            ["TrayProxyReapply"] = "Reapply proxy",
            ["TrayProxyMode"] = "Proxy mode",
            ["TrayModeOff"] = "Clear system proxy",
            ["TrayModeSystem"] = "Auto system proxy",
            ["TrayModeManual"] = "Do not change system proxy",
            ["TrayModePac"] = "PAC mode",
            ["TrayExit"] = "Exit",
            ["ProxyMode"] = "Proxy mode",
            ["ProxyModeOff"] = "Clear system proxy",
            ["ProxyModeSystem"] = "Auto system proxy",
            ["ProxyModeManual"] = "Do not change system proxy",
            ["ProxyModePac"] = "PAC mode",
            ["ApplyWinHttp"] = "Apply WinHTTP together",
            ["ExportEnv"] = "Export environment proxy variables",
            ["PacAddress"] = "PAC address",
            ["ProxyApplied"] = "Proxy applied",
            ["LastProxyApply"] = "Last proxy apply",
            ["ReapplyProxy"] = "Reapply proxy",
            ["ApplyProxy"] = "Save proxy settings",
            ["OpenPac"] = "Open PAC URL",
            ["Applied"] = "Applied",
            ["NotApplied"] = "Not applied",
            ["CurrentProfile"] = "Current profile",
            ["NoActiveProfile"] = "No active profile",
            ["WinHttpState"] = "WinHTTP",
            ["EnvState"] = "Environment",
            ["PacState"] = "PAC",
            ["Enabled"] = "Enabled",
            ["Disabled"] = "Disabled",
            ["PacRunning"] = "Serving",
            ["PacInactive"] = "Inactive",
            ["ProxySummary"] = "Routing summary",
            ["TrafficSummary"] = "Traffic summary",
            ["QuickImport"] = "Quick import",
            ["TrayBehavior"] = "Tray behavior",
            ["CloseToTray"] = "Close to tray",
            ["MinimizeToTray"] = "Minimize to tray",
            ["StartMinimizedToTray"] = "Start minimized to tray",
            ["DiagnosticsReport"] = "Diagnostic report",
            ["CopyDiagnostics"] = "Copy report",
            ["DiagnosticsTargetHint"] = "The copied report includes listeners, WinINet, WinHTTP, environment variables, and tunnel checks.",
            ["SystemPolicy"] = "System proxy policy",
            ["CoreManaged"] = "Core host",
            ["CoreManagedByClient"] = "Managed by desktop client",
            ["CoreManagedExternal"] = "External core detected",
            ["OpenProfiles"] = "Open profiles",
        },
        ["zh-CN"] = new()
        {
            ["AppTitle"] = "MIRAGE",
            ["Tagline"] = "原生 Windows 代理客户端",
            ["Overview"] = "概览",
            ["Profiles"] = "节点",
            ["Diagnostics"] = "诊断",
            ["Settings"] = "设置",
            ["StatusOnline"] = "已连接",
            ["StatusOffline"] = "核心离线",
            ["OverviewTitle"] = "连接概览",
            ["OverviewDesc"] = "一眼看到传输状态、当前代理模式，以及桌面流量接管范围。",
            ["ProfileListTitle"] = "节点",
            ["ProfileListDesc"] = "导入 MIRAGE 节点，并切换当前活动连接。",
            ["DiagnosticsTitle"] = "诊断信息",
            ["DiagnosticsDesc"] = "检查实时代理栈，并在仍有软件绕过 MIRAGE 时一键复制完整报告。",
            ["SettingsTitle"] = "设置",
            ["SettingsDesc"] = "把语言、托盘行为和系统代理策略集中到一个原生设置页里。",
            ["HttpProxy"] = "HTTP / HTTPS",
            ["Socks5"] = "SOCKS5",
            ["Upload"] = "上传",
            ["Download"] = "下载",
            ["Rate"] = "吞吐",
            ["SystemProxy"] = "系统代理",
            ["Import"] = "导入",
            ["Refresh"] = "刷新",
            ["Connect"] = "连接",
            ["Disconnect"] = "断开",
            ["Language"] = "语言",
            ["LanguageSystem"] = "跟随系统",
            ["LanguageZh"] = "中文",
            ["LanguageEn"] = "英文",
            ["CoreVersion"] = "核心版本",
            ["ProtocolVersion"] = "协议版本",
            ["Health"] = "健康状态",
            ["Ready"] = "就绪",
            ["Running"] = "运行中",
            ["LogEmpty"] = "暂时还没有核心日志。",
            ["NoProfiles"] = "还没有导入任何节点。",
            ["ImportHint"] = "粘贴 mirage:// 链接，把节点导入到本地客户端配置中。",
            ["CaptureGap"] = "部分软件仍然需要 TUN 或服务模式，才能达到主流客户端那种接管范围。",
            ["TrayOpen"] = "打开 MIRAGE",
            ["TrayConnect"] = "连接",
            ["TrayDisconnect"] = "断开",
            ["TrayProxyReapply"] = "重新应用代理",
            ["TrayProxyMode"] = "代理模式",
            ["TrayModeOff"] = "清除系统代理",
            ["TrayModeSystem"] = "自动配置系统代理",
            ["TrayModeManual"] = "不修改系统代理",
            ["TrayModePac"] = "PAC 模式",
            ["TrayExit"] = "退出",
            ["ProxyMode"] = "代理模式",
            ["ProxyModeOff"] = "清除系统代理",
            ["ProxyModeSystem"] = "自动配置系统代理",
            ["ProxyModeManual"] = "不修改系统代理",
            ["ProxyModePac"] = "PAC 模式",
            ["ApplyWinHttp"] = "同时应用 WinHTTP",
            ["ExportEnv"] = "导出环境变量代理",
            ["PacAddress"] = "PAC 地址",
            ["ProxyApplied"] = "代理已应用",
            ["LastProxyApply"] = "最近一次代理应用",
            ["ReapplyProxy"] = "重新应用代理",
            ["ApplyProxy"] = "保存代理设置",
            ["OpenPac"] = "打开 PAC 地址",
            ["Applied"] = "已应用",
            ["NotApplied"] = "未应用",
            ["CurrentProfile"] = "当前节点",
            ["NoActiveProfile"] = "暂无活动节点",
            ["WinHttpState"] = "WinHTTP",
            ["EnvState"] = "环境变量",
            ["PacState"] = "PAC",
            ["Enabled"] = "已启用",
            ["Disabled"] = "未启用",
            ["PacRunning"] = "已提供",
            ["PacInactive"] = "未启用",
            ["ProxySummary"] = "路由摘要",
            ["TrafficSummary"] = "流量摘要",
            ["QuickImport"] = "快速导入",
            ["TrayBehavior"] = "托盘行为",
            ["CloseToTray"] = "关闭时最小化到托盘",
            ["MinimizeToTray"] = "最小化时隐藏到托盘",
            ["StartMinimizedToTray"] = "启动时直接进入托盘",
            ["DiagnosticsReport"] = "诊断报告",
            ["CopyDiagnostics"] = "复制报告",
            ["DiagnosticsTargetHint"] = "复制的报告会包含监听器、WinINet、WinHTTP、环境变量和隧道探测结果。",
            ["SystemPolicy"] = "系统代理策略",
            ["CoreManaged"] = "核心托管",
            ["CoreManagedByClient"] = "由桌面客户端托管",
            ["CoreManagedExternal"] = "检测到外部核心",
            ["OpenProfiles"] = "打开节点页",
        }
    };

    public string LanguageCode { get; private set; } = "en-US";

    public event EventHandler? LanguageChanged;

    public void SetLanguage(string code)
    {
        LanguageCode = _translations.ContainsKey(code) ? code : "en-US";
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    public string T(string key)
    {
        if (_translations.TryGetValue(LanguageCode, out var group) &&
            group.TryGetValue(key, out var value))
        {
            return value;
        }

        return key;
    }
}
